spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

---
spring:
  profiles: local
debug: true
